### ISSUE TITLE
how to replace text with emoji 

### ISSUE THREAD

**Issue by bhavanigattikoppula** [Pankaj-Sati/ionic4-emoji-picker#1]
i am try to change the text and emoji positions but every time emoji adding end of the message
for example: hello world
i am try to add emoji in center of hello and world
for example:(hello 😃world) 
but added like 
-->hello world😄 
please help me out this
thanks in advance.

**Comment by Pankaj-Sati** [comment]
Hi @bhavanigattikoppula , Sorry for commenting late.
This emoji picker package doesn't append the selected emoji. You can call a function on the onEmojiSelect event. 
In the example, however, the emojis are added at the end. You can write your own logic to insert at the caret (cursor) position.
