### ISSUE TITLE
Type no modal nos showing

### ISSUE THREAD

**Issue by sjbvsoftware** [Pankaj-Sati/ionic4-emoji-picker#3]
When i add emoji-picker in html as documentation and i set boolean to show to true, emoji-picker never show, its invisible and height is 0 (container height is to 300px correctly)

**Comment by Pankaj-Sati** [comment]
@sjbvsoftware Can you show some of your code? How are you adding the emoji picker?
For reference, you can take a look at this example: https://github.com/Pankaj-Sati/EmojiPicker
It demonstrates both modal and WhatsApp like approach
